@startuml

class Juego
class Jugador
class AI
class Moto
class Tron
class Arena
class Oponente
class Muro
class Jet
class Estela
class Colisionable

Moto o-- Arena
Tron o-- Moto
Oponente o-- Moto

Jugador o-- Tron
AI o-- Oponente

Moto *-- Estela
Arena *-- Muro
Arena *-- Jet

Moto --|> Colisionable
Jet --|> Colisionable
Muro --|> Colisionable
Estela --|> Colisionable


@enduml



